version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: rain_imdb_postgres
    environment:
      POSTGRES_DB: rain_imdb
      POSTGRES_USER: rain_user
      POSTGRES_PASSWORD: rain_password  # In production, use a secure password and environment variables
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rain_user -d rain_imdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rain_imdb_network
    restart: unless-stopped

volumes:
  postgres_data:
    name: rain_imdb_postgres_data

networks:
  rain_imdb_network:
    name: rain_imdb_network
    driver: bridge 